name       : libgames-support
version    : 1.0.2
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libgames-support/1.0/libgames-support-1.0.2.tar.xz : b096e8d8ddc57ff247edc5eae842d405402b043e289f3a0949499e1df514ba66
license    :
    - GPL-3.0
    - LGPL-3.0
component  : desktop.library
summary    : Library intended for use by GNOME Games
description: |
    libgames-support is a small library intended for internal use by GNOME Games, but it may be used by others.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
